features=["driver_historical_completed_bookings", "driver_historical_acceptance_rate", "trip_distance", "driver_distance", "is_Early_Morning", "is_Morning", "is_Midday", "is_Evening", "is_Night", "is_Late_Night", "is_Monday", "is_Tuesday", "is_Wednesday", "is_Thursday", "is_Friday", "is_Saturday", "is_Sunday"]
target="is_completed"
test_size=0.2

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false